import type { ThemePreset } from '../types';

const systemBody =
  'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", "PingFang SC", "Microsoft YaHei", "Noto Sans CJK SC", sans-serif';
const systemCode =
  '"SFMono-Regular", Consolas, "Liberation Mono", Menlo, "Microsoft YaHei UI", monospace';
const editorialSerif =
  '"Iowan Old Style", "Noto Serif SC", "Source Han Serif SC", "Songti SC", STSong, Georgia, "Times New Roman", serif';
const techBody =
  '"Inter", "SF Pro Text", "Segoe UI", "PingFang SC", "Microsoft YaHei", sans-serif';

export const themePresets: ThemePreset[] = [
  {
    id: 'claude',
    name: 'Claude 暖纸',
    description: '暖纸底色、陶土橙点缀和衬线长文排版，适合解释、推理和人文感内容。',
    swatches: ['#faf9f5', '#d97757', '#141413', '#e8e6dc'],
    proseClassName: 'sharkdown-prose--claude',
    cssVars: {
      '--preview-bg': '#faf9f5',
      '--preview-surface': '#f3f1e8',
      '--preview-text': '#141413',
      '--preview-muted': '#6f6a61',
      '--preview-border': '#dedcd1',
      '--preview-accent': '#d97757',
      '--preview-accent-soft': '#f1dfd4',
      '--preview-code-bg': '#e8e6dc',
      '--preview-code-text': '#141413',
      '--preview-shadow': '0 18px 44px rgba(20, 20, 19, 0.12)',
      '--preview-font-body': editorialSerif,
      '--preview-font-heading': editorialSerif,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'gpt',
    name: 'GPT 黑白灰',
    description: '互联网产品式黑白灰、硬朗黑体和低装饰界面，适合干净说明。',
    swatches: ['#ffffff', '#111111', '#6b7280', '#f3f4f6'],
    proseClassName: 'sharkdown-prose--gpt',
    cssVars: {
      '--preview-bg': '#ffffff',
      '--preview-surface': '#f3f4f6',
      '--preview-text': '#111111',
      '--preview-muted': '#6b7280',
      '--preview-border': '#d1d5db',
      '--preview-accent': '#111111',
      '--preview-accent-soft': '#eeeeee',
      '--preview-code-bg': '#f5f5f5',
      '--preview-code-text': '#111111',
      '--preview-shadow': '0 18px 42px rgba(17, 17, 17, 0.1)',
      '--preview-font-body': techBody,
      '--preview-font-heading': techBody,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'apple',
    name: 'Apple 艺术',
    description: 'SF/苹方、克制蓝色、细分割线和大留白，适合精致、现代的展示图。',
    swatches: ['#f5f5f7', '#007aff', '#ffffff', '#1d1d1f'],
    proseClassName: 'sharkdown-prose--apple',
    cssVars: {
      '--preview-bg': '#f5f5f7',
      '--preview-surface': '#ffffff',
      '--preview-text': '#1d1d1f',
      '--preview-muted': '#6e6e73',
      '--preview-border': '#d2d2d7',
      '--preview-accent': '#007aff',
      '--preview-accent-soft': '#e8f2ff',
      '--preview-code-bg': '#ffffff',
      '--preview-code-text': '#1d1d1f',
      '--preview-shadow': '0 24px 70px rgba(29, 29, 31, 0.1)',
      '--preview-font-body': '"SF Pro Text", "PingFang SC", system-ui, sans-serif',
      '--preview-font-heading': '"SF Pro Display", "PingFang SC", system-ui, sans-serif',
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'google',
    name: 'Google 四元色',
    description: '蓝红黄绿品牌四元色和扁平化卡片，适合轻快知识整理。',
    swatches: ['#4285f4', '#ea4335', '#fbbc05', '#34a853'],
    proseClassName: 'sharkdown-prose--google',
    cssVars: {
      '--preview-bg': '#ffffff',
      '--preview-surface': '#f8fafd',
      '--preview-text': '#202124',
      '--preview-muted': '#5f6368',
      '--preview-border': '#dadce0',
      '--preview-accent': '#4285f4',
      '--preview-accent-soft': '#e8f0fe',
      '--preview-code-bg': '#f1f3f4',
      '--preview-code-text': '#202124',
      '--preview-shadow': '0 18px 42px rgba(60, 64, 67, 0.14)',
      '--preview-font-body': '"Google Sans", "Roboto", "PingFang SC", system-ui, sans-serif',
      '--preview-font-heading': '"Google Sans", "Roboto", "PingFang SC", system-ui, sans-serif',
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'wechat',
    name: 'WeChat 清绿',
    description: '微信式清绿、浅灰气泡和高可读黑体，适合社交分享截图。',
    swatches: ['#f7fff9', '#07c160', '#1f2329', '#e9f7ef'],
    proseClassName: 'sharkdown-prose--wechat',
    cssVars: {
      '--preview-bg': '#f7fff9',
      '--preview-surface': '#e9f7ef',
      '--preview-text': '#1f2329',
      '--preview-muted': '#6b7280',
      '--preview-border': '#cfe8d8',
      '--preview-accent': '#07c160',
      '--preview-accent-soft': '#dcf8e7',
      '--preview-code-bg': '#eef7f1',
      '--preview-code-text': '#1f2329',
      '--preview-shadow': '0 18px 46px rgba(7, 193, 96, 0.12)',
      '--preview-font-body': systemBody,
      '--preview-font-heading': systemBody,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'douyin',
    name: 'Douyin 霓虹',
    description: '黑底、青红霓虹撞色和强对比标题，适合短视频封面感截图。',
    swatches: ['#0b0b10', '#25f4ee', '#fe2c55', '#f6f6f6'],
    proseClassName: 'sharkdown-prose--douyin',
    cssVars: {
      '--preview-bg': '#0b0b10',
      '--preview-surface': '#17171f',
      '--preview-text': '#f6f6f6',
      '--preview-muted': '#b8b8c7',
      '--preview-border': '#30303d',
      '--preview-accent': '#25f4ee',
      '--preview-accent-soft': '#132d31',
      '--preview-code-bg': '#12121a',
      '--preview-code-text': '#f6f6f6',
      '--preview-shadow': '0 24px 70px rgba(254, 44, 85, 0.2)',
      '--preview-font-body': techBody,
      '--preview-font-heading': techBody,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'black-gold',
    name: '黑黄会心一笑',
    description: '黑金高对比、黄条强调和直给排版，适合玩笑式强记忆点。',
    swatches: ['#111111', '#ffb000', '#ffffff', '#27272a'],
    proseClassName: 'sharkdown-prose--black-gold',
    cssVars: {
      '--preview-bg': '#111111',
      '--preview-surface': '#27272a',
      '--preview-text': '#ffffff',
      '--preview-muted': '#d4d4d8',
      '--preview-border': '#3f3f46',
      '--preview-accent': '#ffb000',
      '--preview-accent-soft': '#3b2b00',
      '--preview-code-bg': '#1c1c1f',
      '--preview-code-text': '#fff7d6',
      '--preview-shadow': '0 24px 70px rgba(0, 0, 0, 0.34)',
      '--preview-font-body': techBody,
      '--preview-font-heading': techBody,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    description: '干净的文档风格，适合技术说明和 README 片段。',
    swatches: ['#ffffff', '#0969da', '#24292f', '#f6f8fa'],
    cssVars: {
      '--preview-bg': '#ffffff',
      '--preview-surface': '#f6f8fa',
      '--preview-text': '#24292f',
      '--preview-muted': '#57606a',
      '--preview-border': '#d0d7de',
      '--preview-accent': '#0969da',
      '--preview-accent-soft': '#ddf4ff',
      '--preview-code-bg': '#f6f8fa',
      '--preview-code-text': '#24292f',
      '--preview-shadow': '0 18px 50px rgba(31, 35, 40, 0.12)',
      '--preview-font-body': systemBody,
      '--preview-font-heading': systemBody,
      '--preview-font-code': systemCode,
    },
  },
  {
    id: 'paper',
    name: '纸张',
    description: '带有柔和纸感的长文排版，适合知识卡片。',
    swatches: ['#fbf7ef', '#b45309', '#2f2a24', '#f3ead9'],
    cssVars: {
      '--preview-bg': '#fbf7ef',
      '--preview-surface': '#f3ead9',
      '--preview-text': '#2f2a24',
      '--preview-muted': '#74695f',
      '--preview-border': '#ded2bd',
      '--preview-accent': '#b45309',
      '--preview-accent-soft': '#ffedd5',
      '--preview-code-bg': '#efe7d8',
      '--preview-code-text': '#2f2a24',
      '--preview-shadow': '0 18px 44px rgba(120, 83, 42, 0.16)',
      '--preview-font-body': systemBody,
      '--preview-font-heading': '"Georgia", "Times New Roman", "Songti SC", serif',
      '--preview-font-code': systemCode,
    },
  },
];

export function getThemeById(themeId: string): ThemePreset {
  return themePresets.find((theme) => theme.id === themeId) ?? themePresets[0];
}
